[build]
    command = "npm run build"
    publish = "dist"

[context.production.environment]
    NODE_ENV = "production"

[template.environment]
    META_TITLE = "the title of your site"
    META_URL = "the full url, e.g. 'https://emergency-site.dev'"
    META_DESC = "a short description of your site"
    META_LANG = "the language, e.g. 'en', 'de', ..."
    META_COLOR = "the primary color hex code, e.g. '#FF0000'"
    META_EMAIL = "the main contact email address"
    META_TELEPHONE = "the main contact phone number"
    # TZ = "the timezone for your site, e.g. America/New_York"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
